server:
  port: 9002
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            provider:      "facebook"
            client-name:   "Facebook"
            
            client-id:     "[env]"
            client-secret: "[env]"
            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
            
            client-authentication-method: "post"
            
            scope:
              - email
              - public_profile
        provider: 
          facebook:
            authorization-uri: "https://www.facebook.com/dialog/oauth"
            token-uri:         "https://graph.facebook.com/oauth/access_token"
            user-info-uri:     "https://graph.facebook.com/me?fields=id,name,email"
            user-info-authentication-method: "query"

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG